/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as MonitorBitcoinRouteImport } from './routes/monitor.bitcoin'
import { Route as MonitorGoldPriceRouteImport } from './routes/monitor.gold-price'
import { Route as MonitorIphonePriceRouteImport } from './routes/monitor.iphone-price'
import { Route as MonitorTeslaRouteImport } from './routes/monitor.tesla'
import { Route as MonitorUsdRouteImport } from './routes/monitor.usd'
import { Route as AuthenticatedRadarIndexRouteImport } from './routes/_authenticated/radar.index'
import { Route as AuthenticatedRadarIdRouteImport } from './routes/_authenticated/radar.$id'
import { Route as ApiPublicRunMonitorChecksRouteImport } from './routes/api/public/run-monitor-checks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorBitcoinRoute = MonitorBitcoinRouteImport.update({
  id: '/monitor/bitcoin',
  path: '/monitor/bitcoin',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorGoldPriceRoute = MonitorGoldPriceRouteImport.update({
  id: '/monitor/gold-price',
  path: '/monitor/gold-price',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorIphonePriceRoute = MonitorIphonePriceRouteImport.update({
  id: '/monitor/iphone-price',
  path: '/monitor/iphone-price',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorTeslaRoute = MonitorTeslaRouteImport.update({
  id: '/monitor/tesla',
  path: '/monitor/tesla',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorUsdRoute = MonitorUsdRouteImport.update({
  id: '/monitor/usd',
  path: '/monitor/usd',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRadarIndexRoute = AuthenticatedRadarIndexRouteImport.update({
  id: '/radar/',
  path: '/radar/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarIdRoute = AuthenticatedRadarIdRouteImport.update({
  id: '/radar/$id',
  path: '/radar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRunMonitorChecksRoute =
  ApiPublicRunMonitorChecksRouteImport.update({
    id: '/api/public/run-monitor-checks',
    path: '/api/public/run-monitor-checks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/monitor/bitcoin': typeof MonitorBitcoinRoute
  '/monitor/gold-price': typeof MonitorGoldPriceRoute
  '/monitor/iphone-price': typeof MonitorIphonePriceRoute
  '/monitor/tesla': typeof MonitorTeslaRoute
  '/monitor/usd': typeof MonitorUsdRoute
  '/radar/$id': typeof AuthenticatedRadarIdRoute
  '/api/public/run-monitor-checks': typeof ApiPublicRunMonitorChecksRoute
  '/radar/': typeof AuthenticatedRadarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/monitor/bitcoin': typeof MonitorBitcoinRoute
  '/monitor/gold-price': typeof MonitorGoldPriceRoute
  '/monitor/iphone-price': typeof MonitorIphonePriceRoute
  '/monitor/tesla': typeof MonitorTeslaRoute
  '/monitor/usd': typeof MonitorUsdRoute
  '/radar/$id': typeof AuthenticatedRadarIdRoute
  '/api/public/run-monitor-checks': typeof ApiPublicRunMonitorChecksRoute
  '/radar': typeof AuthenticatedRadarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/monitor/bitcoin': typeof MonitorBitcoinRoute
  '/monitor/gold-price': typeof MonitorGoldPriceRoute
  '/monitor/iphone-price': typeof MonitorIphonePriceRoute
  '/monitor/tesla': typeof MonitorTeslaRoute
  '/monitor/usd': typeof MonitorUsdRoute
  '/_authenticated/radar/$id': typeof AuthenticatedRadarIdRoute
  '/api/public/run-monitor-checks': typeof ApiPublicRunMonitorChecksRoute
  '/_authenticated/radar/': typeof AuthenticatedRadarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/monitor/bitcoin'
    | '/monitor/gold-price'
    | '/monitor/iphone-price'
    | '/monitor/tesla'
    | '/monitor/usd'
    | '/radar/$id'
    | '/api/public/run-monitor-checks'
    | '/radar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/monitor/bitcoin'
    | '/monitor/gold-price'
    | '/monitor/iphone-price'
    | '/monitor/tesla'
    | '/monitor/usd'
    | '/radar/$id'
    | '/api/public/run-monitor-checks'
    | '/radar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/monitor/bitcoin'
    | '/monitor/gold-price'
    | '/monitor/iphone-price'
    | '/monitor/tesla'
    | '/monitor/usd'
    | '/_authenticated/radar/$id'
    | '/api/public/run-monitor-checks'
    | '/_authenticated/radar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  MonitorBitcoinRoute: typeof MonitorBitcoinRoute
  MonitorGoldPriceRoute: typeof MonitorGoldPriceRoute
  MonitorIphonePriceRoute: typeof MonitorIphonePriceRoute
  MonitorTeslaRoute: typeof MonitorTeslaRoute
  MonitorUsdRoute: typeof MonitorUsdRoute
  ApiPublicRunMonitorChecksRoute: typeof ApiPublicRunMonitorChecksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/bitcoin': {
      id: '/monitor/bitcoin'
      path: '/monitor/bitcoin'
      fullPath: '/monitor/bitcoin'
      preLoaderRoute: typeof MonitorBitcoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/gold-price': {
      id: '/monitor/gold-price'
      path: '/monitor/gold-price'
      fullPath: '/monitor/gold-price'
      preLoaderRoute: typeof MonitorGoldPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/iphone-price': {
      id: '/monitor/iphone-price'
      path: '/monitor/iphone-price'
      fullPath: '/monitor/iphone-price'
      preLoaderRoute: typeof MonitorIphonePriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/tesla': {
      id: '/monitor/tesla'
      path: '/monitor/tesla'
      fullPath: '/monitor/tesla'
      preLoaderRoute: typeof MonitorTeslaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor/usd': {
      id: '/monitor/usd'
      path: '/monitor/usd'
      fullPath: '/monitor/usd'
      preLoaderRoute: typeof MonitorUsdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/radar/': {
      id: '/_authenticated/radar/'
      path: '/radar'
      fullPath: '/radar/'
      preLoaderRoute: typeof AuthenticatedRadarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar/$id': {
      id: '/_authenticated/radar/$id'
      path: '/radar/$id'
      fullPath: '/radar/$id'
      preLoaderRoute: typeof AuthenticatedRadarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/run-monitor-checks': {
      id: '/api/public/run-monitor-checks'
      path: '/api/public/run-monitor-checks'
      fullPath: '/api/public/run-monitor-checks'
      preLoaderRoute: typeof ApiPublicRunMonitorChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRadarIdRoute: typeof AuthenticatedRadarIdRoute
  AuthenticatedRadarIndexRoute: typeof AuthenticatedRadarIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRadarIdRoute: AuthenticatedRadarIdRoute,
  AuthenticatedRadarIndexRoute: AuthenticatedRadarIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  MonitorBitcoinRoute: MonitorBitcoinRoute,
  MonitorGoldPriceRoute: MonitorGoldPriceRoute,
  MonitorIphonePriceRoute: MonitorIphonePriceRoute,
  MonitorTeslaRoute: MonitorTeslaRoute,
  MonitorUsdRoute: MonitorUsdRoute,
  ApiPublicRunMonitorChecksRoute: ApiPublicRunMonitorChecksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
