/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRadarIndexRouteImport } from './routes/_authenticated/radar.index'
import { Route as AuthenticatedRadarIdRouteImport } from './routes/_authenticated/radar.$id'
import { Route as ApiPublicRunMonitorChecksRouteImport } from './routes/api/public/run-monitor-checks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRadarIndexRoute = AuthenticatedRadarIndexRouteImport.update({
  id: '/radar/',
  path: '/radar/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarIdRoute = AuthenticatedRadarIdRouteImport.update({
  id: '/radar/$id',
  path: '/radar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRunMonitorChecksRoute =
  ApiPublicRunMonitorChecksRouteImport.update({
    id: '/api/public/run-monitor-checks',
    path: '/api/public/run-monitor-checks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/radar/$id': typeof AuthenticatedRadarIdRoute
  '/api/public/run-monitor-checks': typeof ApiPublicRunMonitorChecksRoute
  '/radar/': typeof AuthenticatedRadarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/radar/$id': typeof AuthenticatedRadarIdRoute
  '/api/public/run-monitor-checks': typeof ApiPublicRunMonitorChecksRoute
  '/radar': typeof AuthenticatedRadarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/radar/$id': typeof AuthenticatedRadarIdRoute
  '/api/public/run-monitor-checks': typeof ApiPublicRunMonitorChecksRoute
  '/_authenticated/radar/': typeof AuthenticatedRadarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/radar/$id' | '/api/public/run-monitor-checks' | '/radar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/radar/$id' | '/api/public/run-monitor-checks' | '/radar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/radar/$id'
    | '/api/public/run-monitor-checks'
    | '/_authenticated/radar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicRunMonitorChecksRoute: typeof ApiPublicRunMonitorChecksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/radar/': {
      id: '/_authenticated/radar/'
      path: '/radar'
      fullPath: '/radar/'
      preLoaderRoute: typeof AuthenticatedRadarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar/$id': {
      id: '/_authenticated/radar/$id'
      path: '/radar/$id'
      fullPath: '/radar/$id'
      preLoaderRoute: typeof AuthenticatedRadarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/run-monitor-checks': {
      id: '/api/public/run-monitor-checks'
      path: '/api/public/run-monitor-checks'
      fullPath: '/api/public/run-monitor-checks'
      preLoaderRoute: typeof ApiPublicRunMonitorChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedRadarIdRoute: typeof AuthenticatedRadarIdRoute
  AuthenticatedRadarIndexRoute: typeof AuthenticatedRadarIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedRadarIdRoute: AuthenticatedRadarIdRoute,
  AuthenticatedRadarIndexRoute: AuthenticatedRadarIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicRunMonitorChecksRoute: ApiPublicRunMonitorChecksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
